#ifndef APPLICATION_HPP
#define APPLICATION_HPP

#define APPLICATION_VERSION "1.0.0"
#define APPLICATION_NAME "Sensor Monitor"
#define APPLICATION_NAME_VERSION QString(APPLICATION_NAME) + QString(" v") + QString(APPLICATION_VERSION)
#define APPLICATION_ICON ":/Icons/RS232.png"


#endif // APPLICATION_HPP
